version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432"

  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
