name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install build-essential -y
        apt-get --yes remove postgresql\*
        apt-get install -y postgresql-11 postgresql-client-11
        cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
        service postgresql restart 11
        psql --version
        psql -c 'CREATE DATABASE travis_test_db' -U postgres
        psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
        cp config/test.travis.exs config/test.exs
        cd api
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: |
        cd api
        mix test
